image: ruby:2.6

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - gem install bundler:2.0.2 # this must match the "BUNDLED WITH" clause in Gemfile.lock
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build --destination test --config _config.yml,_config_gitlab.yml
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build --destination public --config _config.yml,_config_gitlab.yml
  artifacts:
    paths:
    - public
  only:
  - master
