title: Grid Bugs
email: admin@gridbugs.org
description: >
  I write down my thoughts about game design, and share progress on games I'm making.
github_username:  stevebob
itch_username: gridbugs

host: 0.0.0.0

header_pages:
  - about.md
  - tags.md

series:
  roguelike-tutorial-2020:
    name: "Roguelike Tutorial 2020"

pagination:
  enabled: true
  per_page: 4
  offset: 0
  permalink: '/page/:num/'
  title: 'Grid Bugs - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 3
    after: 3

permalink: pretty

feed:
  collections:
    - posts

collections_dir: collections

collections:
  roguelike-tutorial-2020:
    output: true
  daily:
    output: true

future: true

defaults:
  -
    values:
      title: ""

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CNAME
  - TODO.md
  - wip_posts/
  - README.md
  - scripts
  - venv
